# Generated by Django 3.2.18 on 2023-03-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thriller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_movie_image', models.ImageField(upload_to='thriller')),
                ('T_movie_rating', models.CharField(max_length=50)),
                ('T_movie_name', models.CharField(max_length=150)),
                ('T_movie_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
