# Generated by Django 3.2.18 on 2023-03-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_thriller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_movie_image', models.ImageField(upload_to='horror')),
                ('H_movie_rating', models.CharField(max_length=50)),
                ('H_movie_name', models.CharField(max_length=150)),
                ('H_movie_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
