# Generated by Django 3.2.18 on 2023-03-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_horror'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_movie_image', models.ImageField(upload_to='action')),
                ('A_movie_rating', models.CharField(max_length=50)),
                ('A_movie_name', models.CharField(max_length=150)),
                ('A_movie_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
