# Generated by Django 3.2.18 on 2023-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_movie_image', models.ImageField(upload_to='comedy')),
                ('C_movie_rating', models.CharField(max_length=50)),
                ('C_movie_name', models.CharField(max_length=150)),
                ('C_movie_genre', models.CharField(max_length=100)),
            ],
        ),
    ]
